package com.coffcat.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("content", "id", Content.class);
		arp.addMapping("datatransmission", "id", Datatransmission.class);
		arp.addMapping("field", "id", Field.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("lt", "id", Lt.class);
		arp.addMapping("makeorder", "id", Makeorder.class);
		arp.addMapping("material", "id", Material.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("meta", "id", Meta.class);
		arp.addMapping("orders", "id", Orders.class);
		arp.addMapping("page", "id", Page.class);
		arp.addMapping("position", "id", Position.class);
		arp.addMapping("power", "id", Power.class);
		arp.addMapping("requirement", "id", Requirement.class);
		arp.addMapping("state", "id", State.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("website", "id", Website.class);
		arp.addMapping("yx", "id", Yx.class);
	}
}

