package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseDatatransmission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Datatransmission extends BaseDatatransmission<Datatransmission> {
	public static final Datatransmission dao = new Datatransmission();
}
