package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseLt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lt extends BaseLt<Lt> {
	public static final Lt dao = new Lt();
	public Lt ltByid(String id){
		Lt lt= dao.findFirst("select * from lt where id=?",id);
		return lt;
	}
}
