package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseMakeorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Makeorder extends BaseMakeorder<Makeorder> {
	public static final Makeorder dao = new Makeorder();
}
