package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Material extends BaseMaterial<Material> {
	public static final Material dao = new Material();
}
