package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseMeta;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Meta extends BaseMeta<Meta> {
	public static final Meta dao = new Meta();
}
