package com.coffcat.common.model;

import com.coffcat.common.model.base.BasePage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Page extends BasePage<Page> {
	public static final Page dao = new Page();
}
