package com.coffcat.common.model;


import com.coffcat.common.model.base.BasePosition;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Position extends BasePosition<Position> {
	public static final Position dao = new Position();
}
