package com.coffcat.common.model;

import com.coffcat.common.model.base.BasePower;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Power extends BasePower<Power> {
	public static final Power dao = new Power();
}
