package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseRequirement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Requirement extends BaseRequirement<Requirement> {
	public static final Requirement dao = new Requirement();
}
