package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseWebsite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Website extends BaseWebsite<Website> {
	public static final Website dao = new Website();
}
