package com.coffcat.common.model;

import com.coffcat.common.model.base.BaseYx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Yx extends BaseYx<Yx> {
	public static final Yx dao = new Yx();
}
