package com.coffcat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMakeorder<M extends BaseMakeorder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setData(java.lang.String data) {
		set("data", data);
	}

	public java.lang.String getData() {
		return get("data");
	}

	public void setUser(java.lang.Integer user) {
		set("user", user);
	}

	public java.lang.Integer getUser() {
		return get("user");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setYxdata(java.lang.String yxdata) {
		set("yxdata", yxdata);
	}

	public java.lang.String getYxdata() {
		return get("yxdata");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setShtype(java.lang.String shtype) {
		set("shtype", shtype);
	}

	public java.lang.String getShtype() {
		return get("shtype");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setShop(java.lang.Integer shop) {
		set("shop", shop);
	}

	public java.lang.Integer getShop() {
		return get("shop");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setPayment(java.lang.String payment) {
		set("payment", payment);
	}

	public java.lang.String getPayment() {
		return get("payment");
	}

	public void setPaytime(java.util.Date paytime) {
		set("paytime", paytime);
	}

	public java.util.Date getPaytime() {
		return get("paytime");
	}

	public void setPayee(java.lang.Integer payee) {
		set("payee", payee);
	}

	public java.lang.Integer getPayee() {
		return get("payee");
	}

	public void setLtpic1(java.lang.String ltpic1) {
		set("ltpic1", ltpic1);
	}

	public java.lang.String getLtpic1() {
		return get("ltpic1");
	}

	public void setLtpic2(java.lang.String ltpic2) {
		set("ltpic2", ltpic2);
	}

	public java.lang.String getLtpic2() {
		return get("ltpic2");
	}

	public void setLtpic3(java.lang.String ltpic3) {
		set("ltpic3", ltpic3);
	}

	public java.lang.String getLtpic3() {
		return get("ltpic3");
	}

	public void setFc(java.lang.Integer fc) {
		set("fc", fc);
	}

	public java.lang.Integer getFc() {
		return get("fc");
	}

	public void setKddh(java.lang.String kddh) {
		set("kddh", kddh);
	}

	public java.lang.String getKddh() {
		return get("kddh");
	}

	public void setToclient(java.lang.String toclient) {
		set("toclient", toclient);
	}

	public java.lang.String getToclient() {
		return get("toclient");
	}

	public void setTag(java.lang.Integer tag) {
		set("tag", tag);
	}

	public java.lang.Integer getTag() {
		return get("tag");
	}

	public void setOrderCreaterid(java.lang.Integer orderCreaterid) {
		set("order_createrid", orderCreaterid);
	}

	public java.lang.Integer getOrderCreaterid() {
		return get("order_createrid");
	}

	public void setOrderCreaterPrentid(java.lang.Integer orderCreaterPrentid) {
		set("order_creater_prentid", orderCreaterPrentid);
	}

	public java.lang.Integer getOrderCreaterPrentid() {
		return get("order_creater_prentid");
	}

	public void setLtdouser(java.lang.Integer ltdouser) {
		set("ltdouser", ltdouser);
	}

	public java.lang.Integer getLtdouser() {
		return get("ltdouser");
	}

	public void setAge(java.lang.String age) {
		set("age", age);
	}

	public java.lang.String getAge() {
		return get("age");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setKg(java.lang.String kg) {
		set("kg", kg);
	}

	public java.lang.String getKg() {
		return get("kg");
	}

	public void setCm(java.lang.String cm) {
		set("cm", cm);
	}

	public java.lang.String getCm() {
		return get("cm");
	}

	public void setYx(java.lang.Integer yx) {
		set("yx", yx);
	}

	public java.lang.Integer getYx() {
		return get("yx");
	}

}
