package com.coffcat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setUser(java.lang.Integer user) {
		set("user", user);
	}

	public java.lang.Integer getUser() {
		return get("user");
	}

	public void setEmtime(java.util.Date emtime) {
		set("emtime", emtime);
	}

	public java.util.Date getEmtime() {
		return get("emtime");
	}

	public void setShop(java.lang.Integer shop) {
		set("shop", shop);
	}

	public java.lang.Integer getShop() {
		return get("shop");
	}

	public void setPd(java.lang.Integer pd) {
		set("pd", pd);
	}

	public java.lang.Integer getPd() {
		return get("pd");
	}

	public void setWantsex(java.lang.String wantsex) {
		set("wantsex", wantsex);
	}

	public java.lang.String getWantsex() {
		return get("wantsex");
	}

	public void setPositionid(java.lang.Integer positionid) {
		set("positionid", positionid);
	}

	public java.lang.Integer getPositionid() {
		return get("positionid");
	}

	public void setPrentqjd(java.lang.Integer prentqjd) {
		set("prentqjd", prentqjd);
	}

	public java.lang.Integer getPrentqjd() {
		return get("prentqjd");
	}

}
