package com.coffcat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLt<M extends BaseLt<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setData(java.lang.String data) {
		set("data", data);
	}

	public java.lang.String getData() {
		return get("data");
	}

	public void setUser(java.lang.Integer user) {
		set("user", user);
	}

	public java.lang.Integer getUser() {
		return get("user");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setOrdersid(java.lang.Integer ordersid) {
		set("ordersid", ordersid);
	}

	public java.lang.Integer getOrdersid() {
		return get("ordersid");
	}

	public void setPic1(java.lang.String pic1) {
		set("pic1", pic1);
	}

	public java.lang.String getPic1() {
		return get("pic1");
	}

	public void setPic2(java.lang.String pic2) {
		set("pic2", pic2);
	}

	public java.lang.String getPic2() {
		return get("pic2");
	}

	public void setPic3(java.lang.String pic3) {
		set("pic3", pic3);
	}

	public java.lang.String getPic3() {
		return get("pic3");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setDouser(java.lang.Integer douser) {
		set("douser", douser);
	}

	public java.lang.Integer getDouser() {
		return get("douser");
	}

}
