package com.coffcat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setPower(java.lang.String power) {
		set("power", power);
	}

	public java.lang.String getPower() {
		return get("power");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setQjdPosition(java.lang.Integer qjdPosition) {
		set("qjd_position", qjdPosition);
	}

	public java.lang.Integer getQjdPosition() {
		return get("qjd_position");
	}

	public void setQjdManager(java.lang.String qjdManager) {
		set("qjd_manager", qjdManager);
	}

	public java.lang.String getQjdManager() {
		return get("qjd_manager");
	}

	public void setQjdManagerTel(java.lang.String qjdManagerTel) {
		set("qjd_manager_tel", qjdManagerTel);
	}

	public java.lang.String getQjdManagerTel() {
		return get("qjd_manager_tel");
	}

	public void setQjdAddress(java.lang.String qjdAddress) {
		set("qjd_address", qjdAddress);
	}

	public java.lang.String getQjdAddress() {
		return get("qjd_address");
	}

	public void setQjdTel(java.lang.String qjdTel) {
		set("qjd_tel", qjdTel);
	}

	public java.lang.String getQjdTel() {
		return get("qjd_tel");
	}

	public void setQjdShopowner(java.lang.String qjdShopowner) {
		set("qjd_shopowner", qjdShopowner);
	}

	public java.lang.String getQjdShopowner() {
		return get("qjd_shopowner");
	}

	public void setQjdShopownerTel(java.lang.String qjdShopownerTel) {
		set("qjd_shopowner_tel", qjdShopownerTel);
	}

	public java.lang.String getQjdShopownerTel() {
		return get("qjd_shopowner_tel");
	}

	public void setSpPrent(java.lang.Integer spPrent) {
		set("sp_prent", spPrent);
	}

	public java.lang.Integer getSpPrent() {
		return get("sp_prent");
	}

	public void setSpAddress(java.lang.String spAddress) {
		set("sp_address", spAddress);
	}

	public java.lang.String getSpAddress() {
		return get("sp_address");
	}

	public void setSpTel(java.lang.String spTel) {
		set("sp_tel", spTel);
	}

	public java.lang.String getSpTel() {
		return get("sp_tel");
	}

	public void setSpShopowner(java.lang.String spShopowner) {
		set("sp_shopowner", spShopowner);
	}

	public java.lang.String getSpShopowner() {
		return get("sp_shopowner");
	}

	public void setSpShopownerTel(java.lang.String spShopownerTel) {
		set("sp_shopowner_tel", spShopownerTel);
	}

	public java.lang.String getSpShopownerTel() {
		return get("sp_shopowner_tel");
	}

	public void setLtSex(java.lang.String ltSex) {
		set("lt_sex", ltSex);
	}

	public java.lang.String getLtSex() {
		return get("lt_sex");
	}

	public void setLtAge(java.lang.String ltAge) {
		set("lt_age", ltAge);
	}

	public java.lang.String getLtAge() {
		return get("lt_age");
	}

	public void setLtTel(java.lang.String ltTel) {
		set("lt_tel", ltTel);
	}

	public java.lang.String getLtTel() {
		return get("lt_tel");
	}

	public void setLtPrent(java.lang.Integer ltPrent) {
		set("lt_prent", ltPrent);
	}

	public java.lang.Integer getLtPrent() {
		return get("lt_prent");
	}

}
