package com.coffcat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseState<M extends BaseState<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCode(java.lang.Integer code) {
		set("code", code);
	}

	public java.lang.Integer getCode() {
		return get("code");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setAdminhtml(java.lang.String adminhtml) {
		set("adminhtml", adminhtml);
	}

	public java.lang.String getAdminhtml() {
		return get("adminhtml");
	}

}
